#!/usr/bin/env python3
"""从 智能体Token消耗数据_20260528.xlsx 生成 agentTokenData.js（无 openpyxl 依赖）。"""
from __future__ import annotations

import json
import zipfile
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
XLSX = ROOT / "智能体Token消耗数据_20260528.xlsx"
OUT = ROOT / "agentTokenData.js"
SHEET_PATH = "xl/worksheets/sheet4.xml"

NS = {"m": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}

# Excel 智能体名称 → data.js agent id
NAME_TO_ID = {
    "告警智能体": "alert",
    "工单智能体": "order",
    "排程智能体": "sched",
    "预警智能体": "warn",
    "巡检智能体": "insp",
    "诊断智能体": "diag",
    "安全智能体": "safe",
    "光伏助手智能体": "pv",
    "问数智能体": "query",
    "运营智能体": "ops",
}

METRIC_KEYS = {
    "今日token消耗总量（累计）": "tokenCumulative",
    "调用次数（累计）": "callsCumulative",
    "成功率": "successRate",
    "推理token（累计）": "reasoningCumulative",
    "工具token（累计）": "toolCumulative",
    "检索token（累计）": "retrievalCumulative",
    "token消耗曲线（小时）": "tokenHourly",
    "使用峰值": "usagePeak",
}


def _read_shared_strings(z: zipfile.ZipFile) -> list[str]:
    sst = ET.fromstring(z.read("xl/sharedStrings.xml"))
    out: list[str] = []
    for si in sst.findall("m:si", NS):
        t = si.find("m:t", NS)
        if t is not None:
            out.append(t.text or "")
        else:
            out.append("".join(x.text or "" for x in si.findall(".//m:t", NS)))
    return out


def _cell_value(c: ET.Element, strings: list[str]):
    t = c.get("t")
    v_el = c.find("m:v", NS)
    if v_el is None or v_el.text is None:
        return ""
    raw = v_el.text
    if t == "s":
        return strings[int(raw)]
    try:
        if "." in raw or "e" in raw.lower():
            return float(raw)
        return int(raw)
    except ValueError:
        return raw


def _parse_sheet(z: zipfile.ZipFile, strings: list[str], sheet_path: str) -> list[list]:
    sheet = ET.fromstring(z.read(sheet_path))
    rows: list[list] = []
    for row in sheet.findall(".//m:sheetData/m:row", NS):
        cells: list = []
        for c in row.findall("m:c", NS):
            cells.append(_cell_value(c, strings))
        rows.append(cells)
    return rows


def _to_float_list(vals: list, n: int = 24) -> list[float]:
    out: list[float] = []
    for x in vals[:n]:
        if x == "" or x is None:
            out.append(0.0)
        else:
            out.append(round(float(x), 4))
    while len(out) < n:
        out.append(0.0)
    return out


def _to_peak_list(vals: list, n: int = 24) -> list:
    out: list = []
    for x in vals[:n]:
        if x == "" or x is None:
            out.append(None)
        else:
            out.append(str(x).strip())
    while len(out) < n:
        out.append(None)
    return out


def parse_agents(rows: list[list]) -> dict:
    by_id: dict = {}
    current_name: str | None = None

    for row in rows[1:]:
        if len(row) < 2:
            continue
        col_a = str(row[0]).strip() if row[0] != "" else ""
        col_b = str(row[1]).strip() if len(row) > 1 and row[1] != "" else ""

        if col_a.endswith("智能体"):
            current_name = col_a
            agent_id = NAME_TO_ID.get(current_name)
            if not agent_id:
                print(f"Warning: unknown agent name {current_name!r}, skipped")
                current_name = None
                continue
            if agent_id not in by_id:
                by_id[agent_id] = {"name": current_name}
            # 首行指标与智能体名同列（A=名称, B=指标名, C..=24h）
            if col_b in METRIC_KEYS:
                key = METRIC_KEYS[col_b]
                vals = row[2:] if len(row) > 2 else []
                if key == "usagePeak":
                    by_id[agent_id][key] = _to_peak_list(vals)
                else:
                    by_id[agent_id][key] = _to_float_list(vals)
            continue

        if not current_name:
            continue

        agent_id = NAME_TO_ID.get(current_name)
        if not agent_id or agent_id not in by_id:
            continue

        if col_b not in METRIC_KEYS:
            continue

        key = METRIC_KEYS[col_b]
        vals = row[2:] if len(row) > 2 else []
        if key == "usagePeak":
            by_id[agent_id][key] = _to_peak_list(vals)
        else:
            by_id[agent_id][key] = _to_float_list(vals)

    for aid, rec in by_id.items():
        for k in METRIC_KEYS.values():
            if k == "usagePeak":
                rec.setdefault(k, [None] * 24)
            else:
                rec.setdefault(k, [0.0] * 24)
    return by_id


def emit_js(by_agent: dict) -> str:
    data_json = json.dumps(by_agent, ensure_ascii=False, indent=2)
    return f"""// Auto-generated by scripts/build-agent-token-data.py — do not edit by hand.
// Source: 智能体Token消耗数据_20260528.xlsx (sheet 03_智能体页)
// Regenerate: python scripts/build-agent-token-data.py

(function () {{
  const BY_AGENT_ID = {data_json};

  function clampHour(h) {{
    const n = Number(h);
    if (!Number.isFinite(n)) return 0;
    return Math.max(0, Math.min(23, Math.floor(n)));
  }}

  function formatTokens(n) {{
    const v = Number(n) || 0;
    if (v >= 1000) {{
      const k = v / 1000;
      return (k >= 100 ? k.toFixed(0) : k >= 10 ? k.toFixed(1) : k.toFixed(2)) + 'K';
    }}
    return String(Math.round(v));
  }}

  /** 00:00~当前小时：对该累计序列各列求和 */
  function sumToHour(series, hourIdx) {{
    const h = clampHour(hourIdx);
    const slice = (series || []).slice(0, h + 1);
    return slice.reduce((s, v) => s + (Number(v) || 0), 0);
  }}

  /** 在 0..hourIdx 范围内取最后一个非空峰值列的下标（即显示小时） */
  function parsePeakHour(usagePeak, hourIdx) {{
    if (!usagePeak || !usagePeak.length) return null;
    const h = clampHour(hourIdx);
    let last = null;
    for (let i = 0; i <= h && i < usagePeak.length; i++) {{
      const v = usagePeak[i];
      if (v !== null && v !== undefined && v !== '') last = i;
    }}
    return last;
  }}

  function getSnapshot(agentId, hourIdx) {{
    const h = clampHour(hourIdx);
    const rec = BY_AGENT_ID[String(agentId)] || null;
    const empty = {{
      hourIdx: h,
      tokenTotal: 0,
      calls: 0,
      successRate: 0,
      peakHour: null,
      spark: [],
      tokensText: '0',
      successRateText: '0.0',
      reasoningTotal: 0,
      toolTotal: 0,
      retrievalTotal: 0,
      reasoningText: '0',
      toolText: '0',
      retrievalText: '0',
      tokenBars: [],
      callsTrend: [],
      callsTrendSpark: [],
    }};
    if (!rec) return empty;

    const tokenTotal = sumToHour(rec.tokenCumulative, h);
    const callsSlice = (rec.callsCumulative || []).slice(0, h + 1);
    const calls = Math.round(sumToHour(rec.callsCumulative, h));
    const successRate = rec.successRate[h] ?? 0;
    const peakHour = parsePeakHour(rec.usagePeak, h);
    const tokenHourlySlice = (rec.tokenHourly || []).slice(0, h + 1);
    const maxV = Math.max(...tokenHourlySlice, 1);
    const spark = tokenHourlySlice.map((v) => v / maxV);

    const reasoningTotal = sumToHour(rec.reasoningCumulative, h);
    const toolTotal = sumToHour(rec.toolCumulative, h);
    const retrievalTotal = sumToHour(rec.retrievalCumulative, h);
    const barMax = Math.max(reasoningTotal, toolTotal, retrievalTotal, 1);
    const tokenBars = [
      {{ key: 'reasoning', pct: (reasoningTotal / barMax) * 100, text: formatTokens(reasoningTotal) }},
      {{ key: 'tool', pct: (toolTotal / barMax) * 100, text: formatTokens(toolTotal) }},
      {{ key: 'retrieval', pct: (retrievalTotal / barMax) * 100, text: formatTokens(retrievalTotal) }},
    ];

    const callsTrend = callsSlice.reduce((arr, v) => {{
      const prev = arr.length ? arr[arr.length - 1] : 0;
      arr.push(prev + (Number(v) || 0));
      return arr;
    }}, []);
    const callsMax = Math.max(...callsTrend, 1);
    const callsTrendSpark = callsTrend.map((v) => v / callsMax);

    return {{
      hourIdx: h,
      tokenTotal,
      calls,
      successRate,
      peakHour,
      spark,
      tokensText: formatTokens(tokenTotal),
      successRateText: Number(successRate).toFixed(1),
      reasoningTotal,
      toolTotal,
      retrievalTotal,
      reasoningText: formatTokens(reasoningTotal),
      toolText: formatTokens(toolTotal),
      retrievalText: formatTokens(retrievalTotal),
      tokenBars,
      callsTrend,
      callsTrendSpark,
    }};
  }}

  window.IRUN_AGENT_TOKEN = {{
    byAgentId: BY_AGENT_ID,
    getSnapshot,
    formatTokens,
    sumToHour,
    parsePeakHour,
    clampHour,
  }};
}})();
"""


def main() -> None:
    if not XLSX.is_file():
        raise SystemExit(f"Missing workbook: {XLSX}")
    with zipfile.ZipFile(XLSX) as z:
        strings = _read_shared_strings(z)
        rows = _parse_sheet(z, strings, SHEET_PATH)
    by_agent = parse_agents(rows)
    OUT.write_text(emit_js(by_agent), encoding="utf-8")
    print(f"Wrote {OUT} ({len(by_agent)} agents)")


if __name__ == "__main__":
    main()
