#!/usr/bin/env python3
"""从 单个电站Token消耗数据_20260528.xlsx 生成 tokenData.js（无 openpyxl 依赖）。"""
from __future__ import annotations

import json
import zipfile
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
XLSX = ROOT / "单个电站Token消耗数据_20260528.xlsx"
OUT = ROOT / "tokenData.js"

NS = {"m": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}

METRIC_KEYS = {
    "今日token消耗总量（累计）": "tokenCumulative",
    "调用时间（h，累计）": "callsCumulative",
    "成功率": "successRate",
    "token消耗曲线（小时）": "tokenHourly",
}


def _read_shared_strings(z: zipfile.ZipFile) -> list[str]:
    sst = ET.fromstring(z.read("xl/sharedStrings.xml"))
    out: list[str] = []
    for si in sst.findall("m:si", NS):
        t = si.find("m:t", NS)
        if t is not None:
            out.append(t.text or "")
        else:
            out.append("".join(x.text or "" for x in si.findall(".//m:t", NS)))
    return out


def _cell_value(c: ET.Element, strings: list[str]) -> str | float:
    t = c.get("t")
    v_el = c.find("m:v", NS)
    if v_el is None or v_el.text is None:
        return ""
    raw = v_el.text
    if t == "s":
        return strings[int(raw)]
    try:
        if "." in raw or "e" in raw.lower():
            return float(raw)
        return int(raw)
    except ValueError:
        return raw


def _parse_sheet(z: zipfile.ZipFile, strings: list[str]) -> list[list]:
    sheet = ET.fromstring(z.read("xl/worksheets/sheet1.xml"))
    rows: list[list] = []
    for row in sheet.findall(".//m:sheetData/m:row", NS):
        cells: list = []
        for c in row.findall("m:c", NS):
            cells.append(_cell_value(c, strings))
        rows.append(cells)
    return rows


def _to_float_list(vals: list, n: int = 24) -> list[float]:
    out: list[float] = []
    for x in vals[:n]:
        if x == "" or x is None:
            out.append(0.0)
        else:
            out.append(round(float(x), 4))
    while len(out) < n:
        out.append(0.0)
    return out


def parse_plants(rows: list[list]) -> dict:
    by_id: dict = {}
    i = 1
    while i < len(rows):
        row = rows[i]
        if len(row) < 6:
            i += 1
            continue
        plant_id = str(row[1]).strip() if row[1] != "" else ""
        metric_name = str(row[4]).strip() if len(row) > 4 else ""
        if plant_id and metric_name in METRIC_KEYS:
            key = METRIC_KEYS[metric_name]
            series = _to_float_list(row[5:])
            if plant_id not in by_id:
                by_id[plant_id] = {
                    "name": str(row[0]).strip(),
                    "capacityKwp": float(row[2]) if row[2] != "" else 0,
                    "mode": str(row[3]).strip() if len(row) > 3 else "",
                }
            by_id[plant_id][key] = series
            i += 1
            continue
        # 续行（同一电站的其余指标）
        if not plant_id and metric_name in METRIC_KEYS and by_id:
            last_id = list(by_id.keys())[-1]
            key = METRIC_KEYS[metric_name]
            by_id[last_id][key] = _to_float_list(row[5:])
        i += 1

    for pid, rec in by_id.items():
        for k in METRIC_KEYS.values():
            rec.setdefault(k, [0.0] * 24)
    return by_id


def emit_js(by_plant: dict) -> str:
  data_json = json.dumps(by_plant, ensure_ascii=False, indent=2)
  return f"""// Auto-generated by scripts/build-token-data.py — do not edit by hand.
// Source: 单个电站Token消耗数据_20260528.xlsx
// Regenerate: python scripts/build-token-data.py

(function () {{
  const BY_PLANT_ID = {data_json};

  function clampHour(h) {{
    const n = Number(h);
    if (!Number.isFinite(n)) return 0;
    return Math.max(0, Math.min(23, Math.floor(n)));
  }}

  function getSnapshot(plantId, hourIdx) {{
    const h = clampHour(hourIdx);
    const rec = BY_PLANT_ID[String(plantId)] || null;
    const empty = {{
      hourIdx: h,
      tokenTotal: 0,
      callsHours: 0,
      successRate: 0,
      tokenHourlySlice: [],
      spark: [],
      tokenTotalK: "0.00",
      callsHoursText: "0.00",
      successRateText: "0.00",
    }};
    if (!rec) return empty;

    const tokenTotal = rec.tokenCumulative[h] ?? 0;
    const callsHours = rec.callsCumulative[h] ?? 0;
    const successRate = rec.successRate[h] ?? 0;
    const tokenHourlySlice = (rec.tokenHourly || []).slice(0, h + 1);
    const maxV = Math.max(...tokenHourlySlice, 1);
    const spark = tokenHourlySlice.map((v) => v / maxV);

    return {{
      hourIdx: h,
      tokenTotal,
      callsHours,
      successRate,
      tokenHourlySlice,
      spark,
      tokenTotalK: (tokenTotal / 1000).toFixed(2),
      callsHoursText: Number(callsHours).toFixed(2),
      successRateText: Number(successRate).toFixed(2),
    }};
  }}

  window.IRUN_TOKEN = {{
    byPlantId: BY_PLANT_ID,
    getSnapshot,
    clampHour,
  }};
}})();
"""


def main() -> None:
    if not XLSX.is_file():
        raise SystemExit(f"Missing workbook: {XLSX}")
    with zipfile.ZipFile(XLSX) as z:
        strings = _read_shared_strings(z)
        rows = _parse_sheet(z, strings)
    by_plant = parse_plants(rows)
    OUT.write_text(emit_js(by_plant), encoding="utf-8")
    print(f"Wrote {OUT} ({len(by_plant)} plants)")


if __name__ == "__main__":
    main()
